[bans]
multiple-versions = "allow"

[licenses]
# List of explicitly allowed licenses
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
]
